PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO django_migrations VALUES(1,'contenttypes','0001_initial','2026-02-23 18:36:39.337194');
INSERT INTO django_migrations VALUES(2,'auth','0001_initial','2026-02-23 18:36:39.367230');
INSERT INTO django_migrations VALUES(3,'admin','0001_initial','2026-02-23 18:36:39.385689');
INSERT INTO django_migrations VALUES(4,'admin','0002_logentry_remove_auto_add','2026-02-23 18:36:39.402128');
INSERT INTO django_migrations VALUES(5,'admin','0003_logentry_add_action_flag_choices','2026-02-23 18:36:39.412215');
INSERT INTO django_migrations VALUES(6,'contenttypes','0002_remove_content_type_name','2026-02-23 18:36:39.433345');
INSERT INTO django_migrations VALUES(7,'auth','0002_alter_permission_name_max_length','2026-02-23 18:36:39.447183');
INSERT INTO django_migrations VALUES(8,'auth','0003_alter_user_email_max_length','2026-02-23 18:36:39.461509');
INSERT INTO django_migrations VALUES(9,'auth','0004_alter_user_username_opts','2026-02-23 18:36:39.472046');
INSERT INTO django_migrations VALUES(10,'auth','0005_alter_user_last_login_null','2026-02-23 18:36:39.487490');
INSERT INTO django_migrations VALUES(11,'auth','0006_require_contenttypes_0002','2026-02-23 18:36:39.493317');
INSERT INTO django_migrations VALUES(12,'auth','0007_alter_validators_add_error_messages','2026-02-23 18:36:39.505112');
INSERT INTO django_migrations VALUES(13,'auth','0008_alter_user_username_max_length','2026-02-23 18:36:39.520289');
INSERT INTO django_migrations VALUES(14,'auth','0009_alter_user_last_name_max_length','2026-02-23 18:36:39.536814');
INSERT INTO django_migrations VALUES(15,'auth','0010_alter_group_name_max_length','2026-02-23 18:36:39.550867');
INSERT INTO django_migrations VALUES(16,'auth','0011_update_proxy_permissions','2026-02-23 18:36:39.561145');
INSERT INTO django_migrations VALUES(17,'auth','0012_alter_user_first_name_max_length','2026-02-23 18:36:39.576366');
INSERT INTO django_migrations VALUES(18,'core','0001_initial','2026-02-23 18:36:39.725410');
INSERT INTO django_migrations VALUES(19,'core','0002_add_is_active_fields','2026-02-23 18:36:39.765107');
INSERT INTO django_migrations VALUES(20,'core','0003_add_is_active_to_sample','2026-02-23 18:36:39.791184');
INSERT INTO django_migrations VALUES(21,'core','0004_biobank_address_biobank_latitude_biobank_longitude_and_more','2026-02-23 18:36:39.934653');
INSERT INTO django_migrations VALUES(22,'core','0005_remove_biobank_address_remove_biobank_country_and_more','2026-02-23 18:36:40.116985');
INSERT INTO django_migrations VALUES(23,'core','0006_rename_keyword_values_sample_keywords_and_more','2026-02-23 18:36:40.160588');
INSERT INTO django_migrations VALUES(24,'core','0007_alter_event_options_and_more','2026-02-23 18:36:40.560607');
INSERT INTO django_migrations VALUES(25,'core','0008_sample_scientific_notes_sample_spectrometry_data_and_more','2026-02-23 18:36:40.625205');
INSERT INTO django_migrations VALUES(26,'core','0009_alter_sample_collection_alter_sample_is_active_and_more','2026-02-23 18:36:40.778384');
INSERT INTO django_migrations VALUES(27,'core','0010_molecularsequence_notebookentry','2026-02-23 18:36:40.823635');
INSERT INTO django_migrations VALUES(28,'core','0011_remove_biobank_created_at_remove_biobank_institution_and_more','2026-02-23 18:36:40.879147');
INSERT INTO django_migrations VALUES(29,'core','0012_biobank_research_group_alter_biobank_visibility','2026-02-23 18:36:40.919822');
INSERT INTO django_migrations VALUES(30,'core','0013_remove_sample_spectrometry_data','2026-02-23 18:36:40.945248');
INSERT INTO django_migrations VALUES(31,'core','0014_chemical','2026-02-23 18:36:40.975870');
INSERT INTO django_migrations VALUES(32,'sessions','0001_initial','2026-02-23 18:36:40.989574');
INSERT INTO django_migrations VALUES(33,'core','0015_sample_derivation_type_sample_parent_sample_and_more','2026-02-25 19:30:07.975188');
INSERT INTO django_migrations VALUES(34,'core','0016_alter_collectionuserrole_unique_together_and_more','2026-02-27 14:28:27.225377');
INSERT INTO django_migrations VALUES(35,'core','0017_bacteria_phage_vector_construction_hostrange','2026-02-27 18:18:22.605904');
INSERT INTO django_migrations VALUES(36,'core','0018_remove_sample_derivation_type_and_more','2026-02-27 19:37:59.714905');
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
INSERT INTO django_admin_log VALUES(1,'1','ICB',1,'[{"added": {}}]',3,1,'2026-02-23 19:36:26.667021');
INSERT INTO django_admin_log VALUES(2,'2','USER1',1,'[{"added": {}}]',4,1,'2026-02-23 19:38:13.119547');
INSERT INTO django_admin_log VALUES(3,'2','USER1',2,'[{"changed": {"fields": ["Groups"]}}]',4,1,'2026-02-23 19:39:22.529675');
INSERT INTO django_admin_log VALUES(4,'3','01_1.3 (Aguardando Recebimento)',3,'',14,1,'2026-02-25 19:38:23.938716');
INSERT INTO django_admin_log VALUES(5,'2','01_1.2 (Aguardando Recebimento)',3,'',14,1,'2026-02-25 19:38:23.938762');
INSERT INTO django_admin_log VALUES(6,'1','01_1.1 (Aguardando Recebimento)',3,'',14,1,'2026-02-25 19:38:23.938799');
INSERT INTO django_admin_log VALUES(7,'5','02 (Aguardando Recebimento)',3,'',14,1,'2026-02-25 20:00:36.337728');
INSERT INTO django_admin_log VALUES(8,'4','Teste (Aguardando Recebimento)',3,'',14,1,'2026-02-25 20:00:36.337785');
INSERT INTO django_admin_log VALUES(9,'7','1234 (Aguardando Recebimento)',3,'',14,1,'2026-02-25 20:17:05.917269');
INSERT INTO django_admin_log VALUES(10,'6','01 (Aguardando Recebimento)',3,'',14,1,'2026-02-25 20:17:05.917340');
INSERT INTO django_admin_log VALUES(11,'1','01 (Aguardando Recebimento)',3,'',24,1,'2026-02-27 18:43:39.967404');
INSERT INTO django_admin_log VALUES(12,'2','01 (Aguardando Recebimento)',3,'',24,1,'2026-02-27 18:46:30.602048');
INSERT INTO django_admin_log VALUES(13,'3','01 (Aguardando Recebimento)',3,'',24,1,'2026-02-27 18:53:31.942203');
INSERT INTO django_admin_log VALUES(14,'5','teste - Sem organismo',3,'',24,1,'2026-02-27 19:40:19.623164');
INSERT INTO django_admin_log VALUES(15,'4','FAGO-2024-001 - vB_EcoP_Gerson01',3,'',24,1,'2026-02-27 19:40:19.623198');
INSERT INTO django_admin_log VALUES(16,'15','teste1 - Entrada',3,'',15,1,'2026-02-27 19:40:39.875698');
INSERT INTO django_admin_log VALUES(17,'1','Teste (TEste)',3,'',10,1,'2026-02-27 19:40:47.100215');
INSERT INTO django_admin_log VALUES(18,'1','TEste',3,'',9,1,'2026-02-27 19:40:51.451605');
INSERT INTO django_admin_log VALUES(19,'6','teste1 - teste',3,'',23,1,'2026-02-27 19:40:56.445924');
INSERT INTO django_admin_log VALUES(20,'1','ICB',3,'',3,1,'2026-02-27 19:41:06.224373');
INSERT INTO django_admin_log VALUES(21,'2','USER1',3,'',4,1,'2026-02-27 19:41:12.122879');
INSERT INTO django_admin_log VALUES(22,'1','53w',3,'',8,1,'2026-02-27 19:41:19.410723');
INSERT INTO django_admin_log VALUES(23,'1','teste',1,'[{"added": {}}]',7,1,'2026-02-27 19:41:46.732471');
INSERT INTO django_admin_log VALUES(24,'1','teste',3,'',7,1,'2026-02-27 19:41:59.085301');
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO django_content_type VALUES(1,'admin','logentry');
INSERT INTO django_content_type VALUES(2,'auth','permission');
INSERT INTO django_content_type VALUES(3,'auth','group');
INSERT INTO django_content_type VALUES(4,'auth','user');
INSERT INTO django_content_type VALUES(5,'contenttypes','contenttype');
INSERT INTO django_content_type VALUES(6,'sessions','session');
INSERT INTO django_content_type VALUES(7,'core','keyword');
INSERT INTO django_content_type VALUES(8,'core','tag');
INSERT INTO django_content_type VALUES(9,'core','biobank');
INSERT INTO django_content_type VALUES(10,'core','collection');
INSERT INTO django_content_type VALUES(11,'core','collectionuserrole');
INSERT INTO django_content_type VALUES(12,'core','keywordvalue');
INSERT INTO django_content_type VALUES(13,'core','researchgroup');
INSERT INTO django_content_type VALUES(14,'core','sample');
INSERT INTO django_content_type VALUES(15,'core','event');
INSERT INTO django_content_type VALUES(16,'core','samplefile');
INSERT INTO django_content_type VALUES(17,'core','biobankuserrole');
INSERT INTO django_content_type VALUES(18,'core','molecularsequence');
INSERT INTO django_content_type VALUES(19,'core','notebookentry');
INSERT INTO django_content_type VALUES(20,'core','chemical');
INSERT INTO django_content_type VALUES(21,'core','construction');
INSERT INTO django_content_type VALUES(22,'core','hostrange');
INSERT INTO django_content_type VALUES(23,'core','bacteria');
INSERT INTO django_content_type VALUES(24,'core','phage');
INSERT INTO django_content_type VALUES(25,'core','vector');
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO auth_permission VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO auth_permission VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO auth_permission VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO auth_permission VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO auth_permission VALUES(5,2,'add_permission','Can add permission');
INSERT INTO auth_permission VALUES(6,2,'change_permission','Can change permission');
INSERT INTO auth_permission VALUES(7,2,'delete_permission','Can delete permission');
INSERT INTO auth_permission VALUES(8,2,'view_permission','Can view permission');
INSERT INTO auth_permission VALUES(9,3,'add_group','Can add group');
INSERT INTO auth_permission VALUES(10,3,'change_group','Can change group');
INSERT INTO auth_permission VALUES(11,3,'delete_group','Can delete group');
INSERT INTO auth_permission VALUES(12,3,'view_group','Can view group');
INSERT INTO auth_permission VALUES(13,4,'add_user','Can add user');
INSERT INTO auth_permission VALUES(14,4,'change_user','Can change user');
INSERT INTO auth_permission VALUES(15,4,'delete_user','Can delete user');
INSERT INTO auth_permission VALUES(16,4,'view_user','Can view user');
INSERT INTO auth_permission VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO auth_permission VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO auth_permission VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO auth_permission VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO auth_permission VALUES(21,6,'add_session','Can add session');
INSERT INTO auth_permission VALUES(22,6,'change_session','Can change session');
INSERT INTO auth_permission VALUES(23,6,'delete_session','Can delete session');
INSERT INTO auth_permission VALUES(24,6,'view_session','Can view session');
INSERT INTO auth_permission VALUES(25,7,'add_keyword','Can add keyword');
INSERT INTO auth_permission VALUES(26,7,'change_keyword','Can change keyword');
INSERT INTO auth_permission VALUES(27,7,'delete_keyword','Can delete keyword');
INSERT INTO auth_permission VALUES(28,7,'view_keyword','Can view keyword');
INSERT INTO auth_permission VALUES(29,8,'add_tag','Can add tag');
INSERT INTO auth_permission VALUES(30,8,'change_tag','Can change tag');
INSERT INTO auth_permission VALUES(31,8,'delete_tag','Can delete tag');
INSERT INTO auth_permission VALUES(32,8,'view_tag','Can view tag');
INSERT INTO auth_permission VALUES(33,9,'add_biobank','Can add biobank');
INSERT INTO auth_permission VALUES(34,9,'change_biobank','Can change biobank');
INSERT INTO auth_permission VALUES(35,9,'delete_biobank','Can delete biobank');
INSERT INTO auth_permission VALUES(36,9,'view_biobank','Can view biobank');
INSERT INTO auth_permission VALUES(37,10,'add_collection','Can add collection');
INSERT INTO auth_permission VALUES(38,10,'change_collection','Can change collection');
INSERT INTO auth_permission VALUES(39,10,'delete_collection','Can delete collection');
INSERT INTO auth_permission VALUES(40,10,'view_collection','Can view collection');
INSERT INTO auth_permission VALUES(41,11,'add_collectionuserrole','Can add Permissão da Collection');
INSERT INTO auth_permission VALUES(42,11,'change_collectionuserrole','Can change Permissão da Collection');
INSERT INTO auth_permission VALUES(43,11,'delete_collectionuserrole','Can delete Permissão da Collection');
INSERT INTO auth_permission VALUES(44,11,'view_collectionuserrole','Can view Permissão da Collection');
INSERT INTO auth_permission VALUES(45,12,'add_keywordvalue','Can add keyword value');
INSERT INTO auth_permission VALUES(46,12,'change_keywordvalue','Can change keyword value');
INSERT INTO auth_permission VALUES(47,12,'delete_keywordvalue','Can delete keyword value');
INSERT INTO auth_permission VALUES(48,12,'view_keywordvalue','Can view keyword value');
INSERT INTO auth_permission VALUES(49,13,'add_researchgroup','Can add research group');
INSERT INTO auth_permission VALUES(50,13,'change_researchgroup','Can change research group');
INSERT INTO auth_permission VALUES(51,13,'delete_researchgroup','Can delete research group');
INSERT INTO auth_permission VALUES(52,13,'view_researchgroup','Can view research group');
INSERT INTO auth_permission VALUES(53,14,'add_sample','Can add sample');
INSERT INTO auth_permission VALUES(54,14,'change_sample','Can change sample');
INSERT INTO auth_permission VALUES(55,14,'delete_sample','Can delete sample');
INSERT INTO auth_permission VALUES(56,14,'view_sample','Can view sample');
INSERT INTO auth_permission VALUES(57,15,'add_event','Can add event');
INSERT INTO auth_permission VALUES(58,15,'change_event','Can change event');
INSERT INTO auth_permission VALUES(59,15,'delete_event','Can delete event');
INSERT INTO auth_permission VALUES(60,15,'view_event','Can view event');
INSERT INTO auth_permission VALUES(61,16,'add_samplefile','Can add sample file');
INSERT INTO auth_permission VALUES(62,16,'change_samplefile','Can change sample file');
INSERT INTO auth_permission VALUES(63,16,'delete_samplefile','Can delete sample file');
INSERT INTO auth_permission VALUES(64,16,'view_samplefile','Can view sample file');
INSERT INTO auth_permission VALUES(65,17,'add_biobankuserrole','Can add Permissão do Biobank');
INSERT INTO auth_permission VALUES(66,17,'change_biobankuserrole','Can change Permissão do Biobank');
INSERT INTO auth_permission VALUES(67,17,'delete_biobankuserrole','Can delete Permissão do Biobank');
INSERT INTO auth_permission VALUES(68,17,'view_biobankuserrole','Can view Permissão do Biobank');
INSERT INTO auth_permission VALUES(69,18,'add_molecularsequence','Can add Molecular Sequence');
INSERT INTO auth_permission VALUES(70,18,'change_molecularsequence','Can change Molecular Sequence');
INSERT INTO auth_permission VALUES(71,18,'delete_molecularsequence','Can delete Molecular Sequence');
INSERT INTO auth_permission VALUES(72,18,'view_molecularsequence','Can view Molecular Sequence');
INSERT INTO auth_permission VALUES(73,19,'add_notebookentry','Can add Notebook Entry');
INSERT INTO auth_permission VALUES(74,19,'change_notebookentry','Can change Notebook Entry');
INSERT INTO auth_permission VALUES(75,19,'delete_notebookentry','Can delete Notebook Entry');
INSERT INTO auth_permission VALUES(76,19,'view_notebookentry','Can view Notebook Entry');
INSERT INTO auth_permission VALUES(77,20,'add_chemical','Can add chemical');
INSERT INTO auth_permission VALUES(78,20,'change_chemical','Can change chemical');
INSERT INTO auth_permission VALUES(79,20,'delete_chemical','Can delete chemical');
INSERT INTO auth_permission VALUES(80,20,'view_chemical','Can view chemical');
INSERT INTO auth_permission VALUES(81,21,'add_construction','Can add Construction');
INSERT INTO auth_permission VALUES(82,21,'change_construction','Can change Construction');
INSERT INTO auth_permission VALUES(83,21,'delete_construction','Can delete Construction');
INSERT INTO auth_permission VALUES(84,21,'view_construction','Can view Construction');
INSERT INTO auth_permission VALUES(85,22,'add_hostrange','Can add Host Range Interaction');
INSERT INTO auth_permission VALUES(86,22,'change_hostrange','Can change Host Range Interaction');
INSERT INTO auth_permission VALUES(87,22,'delete_hostrange','Can delete Host Range Interaction');
INSERT INTO auth_permission VALUES(88,22,'view_hostrange','Can view Host Range Interaction');
INSERT INTO auth_permission VALUES(89,23,'add_bacteria','Can add Bacteria');
INSERT INTO auth_permission VALUES(90,23,'change_bacteria','Can change Bacteria');
INSERT INTO auth_permission VALUES(91,23,'delete_bacteria','Can delete Bacteria');
INSERT INTO auth_permission VALUES(92,23,'view_bacteria','Can view Bacteria');
INSERT INTO auth_permission VALUES(93,24,'add_phage','Can add Phage');
INSERT INTO auth_permission VALUES(94,24,'change_phage','Can change Phage');
INSERT INTO auth_permission VALUES(95,24,'delete_phage','Can delete Phage');
INSERT INTO auth_permission VALUES(96,24,'view_phage','Can view Phage');
INSERT INTO auth_permission VALUES(97,25,'add_vector','Can add Vector');
INSERT INTO auth_permission VALUES(98,25,'change_vector','Can change Vector');
INSERT INTO auth_permission VALUES(99,25,'delete_vector','Can delete Vector');
INSERT INTO auth_permission VALUES(100,25,'view_vector','Can view Vector');
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
INSERT INTO auth_user VALUES(1,'pbkdf2_sha256$1000000$8k8WKkIVLjU8cX9DBqTWYO$kQactq6rdgjakIy9nFHUC4WhVxIHjbTFp7NOuYeQTEA=','2026-02-23 19:28:47.000771',1,'admin','','admin@test.com',1,1,'2026-02-23 18:37:26.794045','');
CREATE TABLE IF NOT EXISTS "core_keyword" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(120) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "core_tag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(120) NOT NULL UNIQUE, "description" text NULL);
CREATE TABLE IF NOT EXISTS "core_keywordvalue" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "value" varchar(255) NOT NULL, "keyword_id" bigint NOT NULL REFERENCES "core_keyword" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_collection_keywords" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "collection_id" bigint NOT NULL REFERENCES "core_collection" ("id") DEFERRABLE INITIALLY DEFERRED, "keywordvalue_id" bigint NOT NULL REFERENCES "core_keywordvalue" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_biobank_keywords" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "biobank_id" bigint NOT NULL REFERENCES "core_biobank" ("id") DEFERRABLE INITIALLY DEFERRED, "keywordvalue_id" bigint NOT NULL REFERENCES "core_keywordvalue" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_researchgroup" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL UNIQUE, "description" text NULL, "created_at" datetime NOT NULL, "coordinator_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_researchgroup_members" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "researchgroup_id" bigint NOT NULL REFERENCES "core_researchgroup" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_sample_tags" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sample_id" bigint NOT NULL REFERENCES "core_sample" ("id") DEFERRABLE INITIALLY DEFERRED, "tag_id" bigint NOT NULL REFERENCES "core_tag" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_event" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "event_type" varchar(50) NOT NULL, "timestamp" datetime NOT NULL, "notes" text NULL, "performed_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "sample_id" bigint NOT NULL REFERENCES "core_sample" ("id") DEFERRABLE INITIALLY DEFERRED, "location_snapshot" varchar(255) NULL);
INSERT INTO core_event VALUES(16,'entry','2026-03-02 14:14:53.858175','Amostra criada: TESTE.',1,7,'FREEZER 1');
CREATE TABLE IF NOT EXISTS "core_collection_tags" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "collection_id" bigint NOT NULL REFERENCES "core_collection" ("id") DEFERRABLE INITIALLY DEFERRED, "tag_id" bigint NOT NULL REFERENCES "core_tag" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_biobank_tags" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "biobank_id" bigint NOT NULL REFERENCES "core_biobank" ("id") DEFERRABLE INITIALLY DEFERRED, "tag_id" bigint NOT NULL REFERENCES "core_tag" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_sample_keywords" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sample_id" bigint NOT NULL REFERENCES "core_sample" ("id") DEFERRABLE INITIALLY DEFERRED, "keywordvalue_id" bigint NOT NULL REFERENCES "core_keywordvalue" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_samplefile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "file" varchar(100) NOT NULL, "description" text NULL, "uploaded_at" datetime NOT NULL, "sample_id" bigint NOT NULL REFERENCES "core_sample" ("id") DEFERRABLE INITIALLY DEFERRED, "mime_type" varchar(100) NULL, "category" varchar(20) NOT NULL, "file_size" bigint NULL);
CREATE TABLE IF NOT EXISTS "core_molecularsequence" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "seq_type" varchar(10) NOT NULL, "sequence_data" text NOT NULL, "description" text NOT NULL, "created_at" datetime NOT NULL, "author_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_notebookentry" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "content" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "author_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_notebookentry_mentions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "notebookentry_id" bigint NOT NULL REFERENCES "core_notebookentry" ("id") DEFERRABLE INITIALLY DEFERRED, "sample_id" bigint NOT NULL REFERENCES "core_sample" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_chemical" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "uuid" char(32) NOT NULL UNIQUE, "name" varchar(255) NOT NULL, "formula" varchar(100) NULL, "cas_number" varchar(50) NULL, "quantity" varchar(50) NOT NULL, "expiry_date" date NULL, "location" varchar(255) NULL, "msds_link" varchar(200) NULL, "hazard_notes" text NULL, "status" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
INSERT INTO django_session VALUES('fkj97fefxrcz81mzjbmwz80r6morzinp','.eJxVjEEOwiAQRe_C2hBnSoG6dN8zNAMzSNVAUtqV8e7apAvd_vfef6mJtjVPW5NlmlldFKjT7xYoPqTsgO9UblXHWtZlDnpX9EGbHivL83q4fweZWv7WzmPqgh9EEluMlqizgD5YM0QXAQkQyCSWQNgHZ89kCH1EMR4YqFfvD-7SOB4:1vuaoM:dw2Rkhtqc_wcpc4ADdfki0wCte63rcARHM3u6ZrRVVU','2026-03-09 18:37:38.210684');
INSERT INTO django_session VALUES('zayvmr6hzhu5j0dl46jmd9ctuq2lc6zo','.eJxVjEEOwiAQRe_C2hBnSoG6dN8zNAMzSNVAUtqV8e7apAvd_vfef6mJtjVPW5NlmlldFKjT7xYoPqTsgO9UblXHWtZlDnpX9EGbHivL83q4fweZWv7WzmPqgh9EEluMlqizgD5YM0QXAQkQyCSWQNgHZ89kCH1EMR4YqFfvD-7SOB4:1vubbr:XgDSj_Q9kE_g1759rW-3XZ3dtaG7RKSOvsKkEqFeLGc','2026-03-09 19:28:47.008650');
CREATE TABLE IF NOT EXISTS "core_biobank" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "is_active" bool NOT NULL, "owner_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "latitude" decimal NULL, "longitude" decimal NULL, "location_label" varchar(255) NOT NULL, "description" text NULL, "research_group_id" bigint NULL REFERENCES "core_researchgroup" ("id") DEFERRABLE INITIALLY DEFERRED, "is_public" bool NOT NULL);
INSERT INTO core_biobank VALUES(2,'teste',1,1,-23.5580320000000007,-46.711826000000002,'Acesso à Ciclovia do Rio Pinheiros, Vila Ida, Alto de Pinheiros, São Paulo, Região Imediata de São Paulo, Região Metropolitana de São Paulo, Região Geográfica Intermediária de São Paulo, São Paulo, 05461-000, Brasil','',NULL,0);
CREATE TABLE IF NOT EXISTS "core_collection" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "description" text NULL, "is_active" bool NOT NULL, "biobank_id" bigint NOT NULL REFERENCES "core_biobank" ("id") DEFERRABLE INITIALLY DEFERRED, "owner_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "is_public" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "core_bacteria" ("sample_ptr_id" bigint NOT NULL PRIMARY KEY REFERENCES "core_sample" ("id") DEFERRABLE INITIALLY DEFERRED, "species" varchar(150) NOT NULL, "strain" varchar(100) NULL, "genotype" text NULL, "resistance_markers" text NOT NULL CHECK ((JSON_VALID("resistance_markers") OR "resistance_markers" IS NULL)), "additional_info" text NULL);
CREATE TABLE IF NOT EXISTS "core_phage" ("sample_ptr_id" bigint NOT NULL PRIMARY KEY REFERENCES "core_sample" ("id") DEFERRABLE INITIALLY DEFERRED, "morphotype" varchar(50) NULL, "taxonomy" varchar(100) NULL, "lifestyle" varchar(50) NULL, "isolation_source" varchar(255) NULL, "genome_type" varchar(20) NULL, "genome_size_bp" integer unsigned NULL CHECK ("genome_size_bp" >= 0), "ncbi_accession" varchar(100) NULL, "temp_C" decimal NULL, "morphology_img" varchar(100) NULL, "genome_sequence" varchar(100) NULL);
INSERT INTO core_phage VALUES(7,'myovirus','tes','lytic','tse','dsDNA',45000,'tse',NULL,'','');
CREATE TABLE IF NOT EXISTS "core_vector" ("sample_ptr_id" bigint NOT NULL PRIMARY KEY REFERENCES "core_sample" ("id") DEFERRABLE INITIALLY DEFERRED, "name_official" varchar(100) NOT NULL, "aliases" text NULL, "vector_type" varchar(50) NULL, "resistance_markers" text NOT NULL CHECK ((JSON_VALID("resistance_markers") OR "resistance_markers" IS NULL)), "induction_system" varchar(100) NULL, "vector_size_bp" integer unsigned NULL CHECK ("vector_size_bp" >= 0), "default_host_id" bigint NULL REFERENCES "core_bacteria" ("sample_ptr_id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_construction" ("sample_ptr_id" bigint NOT NULL PRIMARY KEY REFERENCES "core_sample" ("id") DEFERRABLE INITIALLY DEFERRED, "construction_name" varchar(150) NOT NULL, "insert_name" varchar(100) NULL, "insert_size_bp" integer unsigned NOT NULL CHECK ("insert_size_bp" >= 0), "actual_resistances" text NOT NULL CHECK ((JSON_VALID("actual_resistances") OR "actual_resistances" IS NULL)), "map_file" varchar(100) NULL, "sequence_file" varchar(100) NULL, "origin_lab" varchar(150) NULL, "host_strain_id" bigint NULL REFERENCES "core_bacteria" ("sample_ptr_id") DEFERRABLE INITIALLY DEFERRED, "parent_vector_id" bigint NOT NULL REFERENCES "core_vector" ("sample_ptr_id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_hostrange" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "is_isolation_host" bool NOT NULL, "efficiency_eop" real NULL, "plaque_morphology" varchar(100) NULL, "bacteria_id" bigint NOT NULL REFERENCES "core_bacteria" ("sample_ptr_id") DEFERRABLE INITIALLY DEFERRED, "phage_id" bigint NOT NULL REFERENCES "core_phage" ("sample_ptr_id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "core_sample" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sample_id" varchar(100) NOT NULL UNIQUE, "sample_type" varchar(100) NULL, "organism_name" varchar(255) NULL, "storage_location" varchar(255) NULL, "notes" text NULL, "created_at" datetime NOT NULL, "biobank_id" bigint NULL REFERENCES "core_biobank" ("id") DEFERRABLE INITIALLY DEFERRED, "collection_id" bigint NULL REFERENCES "core_collection" ("id") DEFERRABLE INITIALLY DEFERRED, "owner_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "is_active" bool NOT NULL, "status" varchar(20) NOT NULL, "updated_at" datetime NOT NULL, "uuid" char(32) NOT NULL UNIQUE, "scientific_notes" text NULL, "is_public" bool NOT NULL);
INSERT INTO core_sample VALUES(7,'01','Phage (Virus)','TESTE','FREEZER 1',NULL,'2026-03-02 14:14:53.851943',2,NULL,1,1,'pending','2026-03-02 14:14:53.851980','31a1c019935c4ba09c994aeb9288b7f2','<p><br></p>',0);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('django_migrations',36);
INSERT INTO sqlite_sequence VALUES('django_admin_log',24);
INSERT INTO sqlite_sequence VALUES('django_content_type',25);
INSERT INTO sqlite_sequence VALUES('auth_permission',100);
INSERT INTO sqlite_sequence VALUES('auth_group',1);
INSERT INTO sqlite_sequence VALUES('auth_user',2);
INSERT INTO sqlite_sequence VALUES('core_sample_keywords',0);
INSERT INTO sqlite_sequence VALUES('core_samplefile',0);
INSERT INTO sqlite_sequence VALUES('core_event',16);
INSERT INTO sqlite_sequence VALUES('auth_user_groups',1);
INSERT INTO sqlite_sequence VALUES('core_tag',1);
INSERT INTO sqlite_sequence VALUES('core_biobank',2);
INSERT INTO sqlite_sequence VALUES('core_collection',1);
INSERT INTO sqlite_sequence VALUES('core_sample',7);
INSERT INTO sqlite_sequence VALUES('core_keyword',1);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "core_keywordvalue_keyword_id_e76692a2" ON "core_keywordvalue" ("keyword_id");
CREATE UNIQUE INDEX "core_collection_keywords_collection_id_keywordvalue_id_52eeb105_uniq" ON "core_collection_keywords" ("collection_id", "keywordvalue_id");
CREATE INDEX "core_collection_keywords_collection_id_43b06a06" ON "core_collection_keywords" ("collection_id");
CREATE INDEX "core_collection_keywords_keywordvalue_id_a08cf716" ON "core_collection_keywords" ("keywordvalue_id");
CREATE UNIQUE INDEX "core_biobank_keywords_biobank_id_keywordvalue_id_95c9c5c1_uniq" ON "core_biobank_keywords" ("biobank_id", "keywordvalue_id");
CREATE INDEX "core_biobank_keywords_biobank_id_0bbc5e5f" ON "core_biobank_keywords" ("biobank_id");
CREATE INDEX "core_biobank_keywords_keywordvalue_id_4e3ddc72" ON "core_biobank_keywords" ("keywordvalue_id");
CREATE INDEX "core_researchgroup_coordinator_id_19a7cdc3" ON "core_researchgroup" ("coordinator_id");
CREATE UNIQUE INDEX "core_researchgroup_members_researchgroup_id_user_id_db2cf7db_uniq" ON "core_researchgroup_members" ("researchgroup_id", "user_id");
CREATE INDEX "core_researchgroup_members_researchgroup_id_aa842141" ON "core_researchgroup_members" ("researchgroup_id");
CREATE INDEX "core_researchgroup_members_user_id_3bf3bf63" ON "core_researchgroup_members" ("user_id");
CREATE UNIQUE INDEX "core_sample_tags_sample_id_tag_id_a66aa538_uniq" ON "core_sample_tags" ("sample_id", "tag_id");
CREATE INDEX "core_sample_tags_sample_id_37cf5ee3" ON "core_sample_tags" ("sample_id");
CREATE INDEX "core_sample_tags_tag_id_2c986660" ON "core_sample_tags" ("tag_id");
CREATE INDEX "core_event_performed_by_id_05c8515e" ON "core_event" ("performed_by_id");
CREATE INDEX "core_event_sample_id_1182cb7d" ON "core_event" ("sample_id");
CREATE UNIQUE INDEX "core_collection_tags_collection_id_tag_id_97df6867_uniq" ON "core_collection_tags" ("collection_id", "tag_id");
CREATE INDEX "core_collection_tags_collection_id_e28b10be" ON "core_collection_tags" ("collection_id");
CREATE INDEX "core_collection_tags_tag_id_8a30379c" ON "core_collection_tags" ("tag_id");
CREATE UNIQUE INDEX "core_biobank_tags_biobank_id_tag_id_3f98190e_uniq" ON "core_biobank_tags" ("biobank_id", "tag_id");
CREATE INDEX "core_biobank_tags_biobank_id_775aa661" ON "core_biobank_tags" ("biobank_id");
CREATE INDEX "core_biobank_tags_tag_id_f9e492fc" ON "core_biobank_tags" ("tag_id");
CREATE UNIQUE INDEX "core_sample_keywords_sample_id_keywordvalue_id_f98cd41f_uniq" ON "core_sample_keywords" ("sample_id", "keywordvalue_id");
CREATE INDEX "core_sample_keywords_sample_id_42a27967" ON "core_sample_keywords" ("sample_id");
CREATE INDEX "core_sample_keywords_keywordvalue_id_e1019b43" ON "core_sample_keywords" ("keywordvalue_id");
CREATE INDEX "core_samplefile_sample_id_d17ab454" ON "core_samplefile" ("sample_id");
CREATE INDEX "core_molecularsequence_author_id_3516d4c6" ON "core_molecularsequence" ("author_id");
CREATE INDEX "core_notebookentry_author_id_b165d971" ON "core_notebookentry" ("author_id");
CREATE UNIQUE INDEX "core_notebookentry_mentions_notebookentry_id_sample_id_868d5b35_uniq" ON "core_notebookentry_mentions" ("notebookentry_id", "sample_id");
CREATE INDEX "core_notebookentry_mentions_notebookentry_id_56fed5a4" ON "core_notebookentry_mentions" ("notebookentry_id");
CREATE INDEX "core_notebookentry_mentions_sample_id_c3068483" ON "core_notebookentry_mentions" ("sample_id");
CREATE INDEX "core_chemical_created_by_id_b456af1e" ON "core_chemical" ("created_by_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "core_biobank_owner_id_11644289" ON "core_biobank" ("owner_id");
CREATE INDEX "core_biobank_research_group_id_04e3a333" ON "core_biobank" ("research_group_id");
CREATE INDEX "core_collection_biobank_id_880fbac8" ON "core_collection" ("biobank_id");
CREATE INDEX "core_collection_owner_id_413893f9" ON "core_collection" ("owner_id");
CREATE INDEX "core_vector_default_host_id_15fd3af4" ON "core_vector" ("default_host_id");
CREATE INDEX "core_construction_host_strain_id_f58473d2" ON "core_construction" ("host_strain_id");
CREATE INDEX "core_construction_parent_vector_id_8f5fb1c0" ON "core_construction" ("parent_vector_id");
CREATE UNIQUE INDEX "core_hostrange_phage_id_bacteria_id_edf60599_uniq" ON "core_hostrange" ("phage_id", "bacteria_id");
CREATE INDEX "core_hostrange_bacteria_id_062a2aaf" ON "core_hostrange" ("bacteria_id");
CREATE INDEX "core_hostrange_phage_id_85247412" ON "core_hostrange" ("phage_id");
CREATE INDEX "core_sample_biobank_id_3f02f856" ON "core_sample" ("biobank_id");
CREATE INDEX "core_sample_collection_id_659b42b6" ON "core_sample" ("collection_id");
CREATE INDEX "core_sample_owner_id_fc980c7d" ON "core_sample" ("owner_id");
COMMIT;
